### ISSUE TITLE
One Page Booking Form

### ISSUE THREAD

**Issue by adjhduane** [mdjmplugin/mobile-dj-manager#193] opened 2017-07-14 11:36 UTC
Single page booking form for client to complete on the front end.
Similar to the pictures attached.

Client checks availability and it shows only the available options on a single page booking form with available add-ons.

![screen shot 2017-07-14 at 12 34 13](https://user-images.githubusercontent.com/30176423/28210753-e5d9e924-6890-11e7-8f82-9c5754a30e8b.png)
![screen shot 2017-07-14 at 12 34 37](https://user-images.githubusercontent.com/30176423/28210754-e695fa42-6890-11e7-8834-795c92c1ca24.png)

**Comment by mikeyhoward1977** [comment] 2017-07-14 11:40
Duplicate of #190

**Closed as completed by mikeyhoward1977** 2017-07-14 11:40 UTC
