### ISSUE TITLE
Error - change status of event to Awaiting Contract

### ISSUE THREAD

**Issue by petrknap1** [mdjmplugin/mobile-dj-manager#34] opened 2016-05-16 15:07 UTC
If I change status of event to Awaiting Contract then WP show me this error message and email with contract doesn't send to a client. I use WP 4.5.2.
Thank you.
![error](https://cloud.githubusercontent.com/assets/19391308/15293441/3fab9602-1b88-11e6-9249-a25622477f58.jpg)

**Comment by mikeyhoward1977** [comment] 2016-05-16 15:39
Hello,

Thanks for posting...Are you able to provide any more information on this?

Did you transition from the admin interface or the front end?

I do not see this (nor have I had any other reports). Are you able to enable MDJM Debugging and it would also be useful for you to enable WP Debugging if you know how. If you then let me know your web address I can review the contents.

Can you also tell me what the original event status was before you changed to Awaiting Contract?

The error above is only generated in two places and both are from the use of shortcodes

If you'd rather, send me an admin login (make sure to edit my user and set to MDJM Admin and set a role) to your site together with your URL

Thanks

**Comment by petrknap1** [comment] 2016-05-16 16:15
Hello,

I use admin interface. MDJM Debugging is enable now. Original event status was "Cancelled". 
It was okay before update MDJM to 1.3xxx version.
My website: www.kv-production.cz and Client zone is here: http://www.kv-production.cz/client-zone/

Thank you.

**Comment by mikeyhoward1977** [comment] 2016-05-16 16:33
Thanks.

I can't re-produce :(

I think this is the same as [issue #35](https://github.com/mydjplanner/mobile-dj-manager/issues/35). I will close this issue and use #35 instead to save duplication.

I plan to push a release later today/early tomorrow. If the issue is not resolved after that, let me know

**Closed as completed by mikeyhoward1977** 2016-05-16 16:33 UTC
